#ifndef SMDH_H
#define SMDH_H

#include "types.h"

#define SMDH_MAGIC "SMDH"

#define SMDH_NUM_LANGUAGE_SLOTS 16
#define SMDH_NUM_VALID_LANGUAGE_SLOTS 12

#define SMDH_SMALL_ICON_DIM 24
#define SMDH_SMALL_ICON_SIZE (SMDH_SMALL_ICON_DIM * SMDH_SMALL_ICON_DIM)
#define SMDH_LARGE_ICON_DIM 48
#define SMDH_LARGE_ICON_SIZE (SMDH_LARGE_ICON_DIM * SMDH_LARGE_ICON_DIM)

enum SMDHLanguage {
	SMDH_LANGUAGE_JAPANESE = 0,
	SMDH_LANGUAGE_ENGLISH,
	SMDH_LANGUAGE_FRENCH,
	SMDH_LANGUAGE_GERMAN,
	SMDH_LANGUAGE_ITALIAN,
	SMDH_LANGUAGE_SPANISH,
	SMDH_LANGUAGE_SIMPLIFIED_CHINESE,
	SMDH_LANGUAGE_KOREAN,
	SMDH_LANGUAGE_DUTCH,
	SMDH_LANGUAGE_PORTUGUESE,
	SMDH_LANGUAGE_RUSSIAN,
	SMDH_LANGUAGE_TRADITIONAL_CHINESE
};

enum SMDHRating {
	SMDH_RATING_CERO = 0,
	SMDH_RATING_ESRB = 1,
	SMDH_RATING_USK = 3,
	SMDH_RATING_PEGI_GEN = 4,
	SMDH_RATING_PEGI_PTR = 6,
	SMDH_RATING_PEGI_BBFC = 7,
	SMDH_RATING_COB = 8,
	SMDH_RATING_GRB = 9,
	SMDH_RATING_CGSRR = 10
};

enum SMDHRegion {
	SMDH_REGION_JAPAN = BITNUM(0),
	SMDH_REGION_NORTH_AMERICA = BITNUM(1),
	SMDH_REGION_EUROPE = BITNUM(2),
	SMDH_REGION_AUSTRALIA = BITNUM(3),
	SMDH_REGION_CHINA = BITNUM(4),
	SMDH_REGION_KOREA = BITNUM(5),
	SMDH_REGION_TAIWAN = BITNUM(6),

	// Not a bitmask, but a value.
	SMDH_REGION_FREE = 0x7FFFFFFF
};

enum SMDHFlag {
	SMDH_FLAG_VISIBLE = BITNUM(0),
	SMDH_FLAG_AUTO_BOOT = BITNUM(1),
	SMDH_FLAG_ALLOW_3D = BITNUM(2),
	SMDH_FLAG_REQUIRE_EULA = BITNUM(3),
	SMDH_FLAG_AUTO_SAVE_ON_EXIT = BITNUM(4),
	SMDH_FLAG_USE_EXTENDED_BANNER = BITNUM(5),
	SMDH_FLAG_RATING_REQUIED = BITNUM(6),
	SMDH_FLAG_USE_SAVE_DATA = BITNUM(7),
	SMDH_FLAG_RECORD_USAGE = BITNUM(8),
	SMDH_FLAG_DISABLE_SAVE_BACKUPS = BITNUM(10), // FIXME: bit 9 in smdhtool // c1
	SMDH_FLAG_NEW_3DS = BITNUM(12)
};

typedef struct {
	u16 shortTitle[0x40];
	u16 longTitle[0x80];
	u16 publisher[0x40];
} SMDHTitle;

#define SMDH_NUM_RATING_SLOTS 16

typedef struct {
	u8 gameRatings[SMDH_NUM_RATING_SLOTS];
	u32 regionLock;
	u32 matchMakerId;
	u64 matchMakerBitId;
	u32 flags;
	u16 eulaVersion;
	u16 reserved1;
	u32 optimalBannerFrame;
	u32 streetpassId;
} SMDHSettings;

typedef struct {
	char magic[4];
	u16 version;
	u16 reserved0;
	SMDHTitle titles[SMDH_NUM_LANGUAGE_SLOTS];
	SMDHSettings settings;
	u64 reserved1;
	u16 smallIcon[SMDH_SMALL_ICON_SIZE];
	u16 largeIcon[SMDH_LARGE_ICON_SIZE];
} SMDH;

#endif
